name: Deploy infrastructure development

on:
    push:
        branches: [main]

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Deploy nginx
              run: sudo docker run -d --name servidor-web -p 80:80 nginx